# Generated by Django 4.0.6 on 2023-07-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='earning',
            field=models.FloatField(default=0.0),
        ),
    ]
